[meta]
id          = "catppuccin-mocha"
name        = "Catppuccin Mocha"
mode        = "dark"
default     = false
author      = "Catppuccin team"
license     = "MIT"
upstream    = "https://github.com/catppuccin/catppuccin"

[base]
bg          = "#1E1E2E"  # base
bg_alt      = "#181825"  # mantle
surface     = "#313244"  # surface0
surface_2   = "#45475A"  # surface1
fg          = "#CDD6F4"  # text
fg_dim      = "#A6ADC8"  # subtext0
border      = "#45475A"

[accent]
primary     = "#CBA6F7"  # mauve
secondary   = "#89B4FA"  # blue
tertiary    = "#F5C2E7"  # pink

[state]
warn        = "#F9E2AF"  # yellow
error       = "#F38BA8"  # red
success     = "#A6E3A1"  # green
info        = "#89DCEB"  # sky

[terminal]
black         = "#45475A"
red           = "#F38BA8"
green         = "#A6E3A1"
yellow        = "#F9E2AF"
blue          = "#89B4FA"
magenta       = "#F5C2E7"
cyan          = "#94E2D5"
white         = "#BAC2DE"
bright_black  = "#585B70"
bright_red    = "#F38BA8"
bright_green  = "#A6E3A1"
bright_yellow = "#F9E2AF"
bright_blue   = "#89B4FA"
bright_magenta= "#F5C2E7"
bright_cyan   = "#94E2D5"
bright_white  = "#A6ADC8"
